name: DotNet Build

on:
  push:
    branches:
      - release
      - main
    tags:
      - "!*"
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - main
jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build ./src/Web/ -c Release
#      - name: Test
#        run: dotnet test ./src/Web.Tests/ -c Release
